version: '3.2'
services:
    alarm-server:
        image: lnlscon/mail-proxy:latest
        hostname: mail-proxy
        dns:
            - 10.0.0.71
            - 10.0.0.72
        deploy:
            resources:
              limits:
                cpus: "2"
                memory: 1024M
